DROP USER CBMADM CASCADE;

CREATE USER CBMADM IDENTIFIED BY "CBMADM";

GRANT CONNECT, CREATE ANY TABLE, DROP ANY TABLE, CREATE PUBLIC SYNONYM TO CBMADM;

ALTER USER "CBMADM"
DEFAULT TABLESPACE "DATA_ROT"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

ALTER USER "CBMADM" QUOTA UNLIMITED ON "DATA_ROT";

QUIT
/
