DROP USER CBMGTW CASCADE;

CREATE USER CBMGTW IDENTIFIED BY "CBMGTW";

GRANT CONNECT TO CBMGTW;

ALTER USER "CBMGTW"
DEFAULT TABLESPACE "DATA_ROT"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

ALTER USER "CBMGTW" QUOTA UNLIMITED ON "DATA_ROT";

QUIT
/
