
-------------------------------------------------------
--  DDL for Table
--------------------------------------------------------

CREATE TABLE "CBMADM"."OCS_EVENTS" (
	   EVENT_ID NUMBER,
	   EVENT_TYPE NUMBER,
	   EVENT_DATE DATE,
	   MSISDN VARCHAR2(100),
	   EXPIRE_DATE DATE,
	   VALUE NUMBER,
	   INITIAL_AMOUNT NUMBER,
	   NEXT_PIR VARCHAR2(100),
	   START_DATE DATE,
	   ACCOUNTID1 VARCHAR2(100),
	   ACCOUNTID2 VARCHAR2(100),
	   ENTRY_DATE DATE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS NOLOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ;

COMMENT ON TABLE "CBMADM"."OCS_EVENTS"  IS 'Event table for OCS messages loaded from the queue';
COMMENT ON COLUMN "CBMADM"."OCS_EVENTS"."EVENT_ID" IS 'Unique id of the event';

--------------------------------------------------------
--  DDL for Index
--------------------------------------------------------

CREATE UNIQUE INDEX "CBMADM"."PK_OCS_EVT_IDX" ON "CBMADM"."OCS_EVENTS" ("EVENT_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT" ;

--------------------------------------------------------
--  DDL for Constraints
--------------------------------------------------------

ALTER TABLE "CBMADM"."OCS_EVENTS"
ADD CONSTRAINT "PK_OCS_EVT_IDX" PRIMARY KEY ("EVENT_ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "DATA_ROT"  ENABLE;

ALTER TABLE "CBMADM"."OCS_EVENTS" MODIFY ("EVENT_ID" NOT NULL ENABLE);
ALTER TABLE "CBMADM"."OCS_EVENTS" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
ALTER TABLE "CBMADM"."OCS_EVENTS" MODIFY ("EVENT_DATE" NOT NULL ENABLE);
ALTER TABLE "CBMADM"."OCS_EVENTS" MODIFY ("MSISDN" NOT NULL ENABLE);
ALTER TABLE "CBMADM"."OCS_EVENTS" MODIFY ("EXPIRE_DATE" NOT NULL ENABLE);
ALTER TABLE "CBMADM"."OCS_EVENTS" MODIFY ("VALUE" NOT NULL ENABLE);
ALTER TABLE "CBMADM"."OCS_EVENTS" MODIFY ("INITIAL_AMOUNT" NOT NULL ENABLE);
ALTER TABLE "CBMADM"."OCS_EVENTS" MODIFY ("NEXT_PIR" NOT NULL ENABLE);
ALTER TABLE "CBMADM"."OCS_EVENTS" MODIFY ("START_DATE" NOT NULL ENABLE);
ALTER TABLE "CBMADM"."OCS_EVENTS" MODIFY ("ACCOUNTID1" NOT NULL ENABLE);
ALTER TABLE "CBMADM"."OCS_EVENTS" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Grants
--------------------------------------------------------

GRANT SELECT, INSERT ON "CBMADM"."OCS_EVENTS" TO CBMGTW;

--------------------------------------------------------
--  DDL for Synoyms
--------------------------------------------------------

CREATE OR REPLACE PUBLIC SYNONYM OCS_EVENTS FOR "CBMADM"."OCS_EVENTS";

QUIT
